=== seasarorg/uruma-www/src/main/resources/org/seasar/jface/template/s2jface01.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
-->
<!ELEMENT template (window)>
<!ATTLIST template name CDATA #REQUIRED>

<!ELEMENT window (composite | control | property)*>
<!ATTLIST window id CDATA #REQUIRED>
<!ATTLIST window title CDATA #IMPLIED>
<!ATTLIST window x CDATA #IMPLIED>
<!ATTLIST window y CDATA #IMPLIED>
<!ATTLIST window width CDATA #IMPLIED>
<!ATTLIST window height CDATA #IMPLIED>
<!ATTLIST window maxButton (true | false) "true">
<!ATTLIST window minButton (true | false) "true">
<!ATTLIST window closeButton (true | false) "true">
<!ATTLIST window resizable (true | false) "true">
<!ATTLIST window image CDATA #IMPLIED>
<!ATTLIST window layout CDATA #IMPLIED>
<!ATTLIST window layoutParam CDATA #IMPLIED>

<!ELEMENT control (property | layoutData)*>
<!ATTLIST control type CDATA #REQUIRED>
<!ATTLIST control id CDATA #IMPLIED>
<!ATTLIST control style CDATA #IMPLIED>

<!ELEMENT composite (composite | control | property | layoutData)*>
<!ATTLIST composite type CDATA #REQUIRED>
<!ATTLIST composite id CDATA #IMPLIED>
<!ATTLIST composite style CDATA #IMPLIED>
<!ATTLIST composite layout CDATA #IMPLIED>
<!ATTLIST composite layoutParam CDATA #IMPLIED>

<!ELEMENT property EMPTY>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #REQUIRED>
<!ATTLIST property inheritance (none | child | descendant) #IMPLIED>

<!ELEMENT layoutData EMPTY>
<!ATTLIST layoutData name CDATA #REQUIRED>
<!ATTLIST layoutData value CDATA #REQUIRED>

=== seasarorg/uruma-www/src/test/resources/org/seasar/jface/renderer/LabelRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="labelRendererTest">
  <window id="labelRendererTest" title="LabelRendererTest" x="center"
    y="middle" layout="row"
    layoutParam="type=VERTICAL; marginHeight=10; marginWidth=10; spacing=10">
    <property name="fontSize" value="20" />

    <control type="label">
      <property name="text" value="ラベル" />
      <property name="toolTip" value="ツールチップテキスト" />
    </control>

    <control type="label" style="BORDER">
      <property name="text" value="枠付きラベル" />
    </control>

    <control type="label">
      <property name="image" value="../template/container.gif" />
    </control>

    <control type="label" style="BORDER">
      <property name="text" value="複数行テキスト1行目\n\t複数行テキスト2行目\n3行目" />
    </control>

    <control type="label" style="WRAP, BORDER">
      <property name="text"
        value="WRAPスタイルを適用することで、長い文字列は折り返して表示されます。" />
      <property name="fontSize" value="12" />
      <layoutData name="width" value="200" />
      <layoutData name="height" value="100" />

    </control>
  </window>
</template>

=== seasarorg/uruma-www/src/test/resources/org/seasar/jface/renderer/ButtonRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="buttonRendererTest">
  <window id="buttonRendererTest" title="ButtonRendererTest" x="center"
    y="middle" layout="row"
    layoutParam="type=HORIZONTAL; marginHeight=10; marginWidth=10; spacing=10">
    <property name="fontSize" value="20" />

    <composite type="box" layout="row"
      layoutParam="type=VERTICAL; spacing=10">
      <!-- styleを省略した場合、style="PUSH" となります -->
      <control type="button">
        <property name="text" value="プッシュボタン" />
        <property name="toolTip" value="ツールチップテキスト" />
      </control>

      <control type="button" style="FLAT">
        <property name="text" value="フラットボタン" />
      </control>

      <control type="button" style="RADIO">
        <property name="text" value="ラジオボタン" />
      </control>

      <control type="button" style="CHECK">
        <property name="text" value="チェックボタン" />
      </control>

      <control type="button" style="TOGGLE">
        <property name="text" value="トグルボタン" />
      </control>
    </composite>

    <composite type="box" layout="row"
      layoutParam="type=VERTICAL; spacing=10">

      <control type="button" style="ARROW, UP">
        <property name="width" value="30" />
        <property name="height" value="30" />
      </control>

      <control type="button" style="ARROW, RIGHT">
        <property name="width" value="30" />
        <property name="height" value="30" />
      </control>

      <control type="button" style="ARROW, DOWN">
        <property name="width" value="30" />
        <property name="height" value="30" />
      </control>

      <control type="button" style="ARROW, LEFT">
        <property name="width" value="30" />
        <property name="height" value="30" />
      </control>
    </composite>
  </window>
</template>

=== seasarorg/uruma-www/src/test/resources/org/seasar/jface/renderer/CustomTabRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="customTabRendererTest" extends="RendererTest.xml">
  <extends id="customTabRendererTest" property="title">
    CustomTabRendererTest
  </extends>
  <extends id="contents" />
  
  <window id="customTabRendererTest">
    <composite id="contents" type="box">
      <composite type="box" layout="fill"
        layoutParam="type=HORIZONTAL; marginHeight=10; marginWidth=10; spacing=10">
        <layoutData name="horizontalAlignment">FILL</layoutData>

        <control type="customTab">
          <property name="simpleStyle">true</property>
          <property name="text">tab1-1, tab1-2</property>
        </control>

        <control type="customTab">
          <property name="closeButton">true</property>
          <property name="text">tab2-1, tab2-2, tab2-3</property>
        </control>
      </composite>
    </composite>
  </window>
</template>

=== seasarorg/uruma-www/src/test/resources/org/seasar/jface/events/eventListenerTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="EventListenrTest">
	<window id="eventListenerTest" layout="grid"
		layoutParam="numColumns=2">
		<composite type="box" layout="fill"
			layoutParam="spacing=20; marginWidth=20">
			<layoutData name="horizontalSpan">2</layoutData>
			<control type="button" id="go">
				<property name="text">Go!</property>
			</control>
			<control type="button" id="stop">
				<property name="text">Stop!</property>
			</control>
		</composite>
	</window>
</template>

=== seasarorg/uruma-www/src/test/resources/org/seasar/jface/renderer/TableRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="tableRendererTest">
  <window id="tableRendererTest" title="tableRendererTest" x="center"
    y="middle" minButton="false" maxButton="false" closeButton="false"
    resizable="false" layout="grid" layoutParam="numColumns=1">
    <property name="defaultButton">okButton</property>

    <composite type="box" layout="row"
      layoutParam="type=HORIZONTAL; marginHeight=10; marginWidth=10; spacing=10">
      <layoutData name="horizontalAlignment">FILL</layoutData>

      <control type="table" style="BORDER">
        <property name="width">200</property>
        <property name="height">100</property>
        <property name="header">head1, head2, head3</property>
        <item>column1, column2, column3</item>
        <item>column4, column5, column6</item>
      </control>
    </composite>

    <control type="label" style="SEPARATOR, HORIZONTAL">
      <layoutData name="horizontalAlignment">FILL</layoutData>
    </control>

    <composite type="box" layout="fill"
      layoutParam="type=HORIZONTAL; spacing=5">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <control type="button" id="okButton">
        <property name="text">OK</property>
      </control>
      <control type="button" id="ngButton">
        <property name="text">NG</property>
      </control>
    </composite>

  </window>
</template>

=== seasarorg/uruma-www/src/test/resources/org/seasar/jface/renderer/GroupRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="groupRendererTest">
  <window id="groupRendererTest" title="groupRendererTest" x="center"
    y="middle" minButton="false" maxButton="false" closeButton="false"
    resizable="false" layout="grid" layoutParam="numColumns=1">
    <property name="defaultButton">okButton</property>

    <composite type="box" layout="row"
      layoutParam="type=HORIZONTAL; marginHeight=10; marginWidth=10; spacing=10">
      <property name="fontSize">20</property>
      <layoutData name="horizontalAlignment">FILL</layoutData>

      <composite type="group" layout="row"
        layoutParam="type=VERTICAL; spacing=10">
        <property name="text">グループ1</property>

        <control type="button" style="RADIO">
          <property name="text">ラジオボタン1</property>
        </control>

        <control type="button" style="RADIO">
          <property name="text">ラジオボタン2</property>
        </control>

        <control type="button" style="RADIO">
          <property name="text">ラジオボタン3</property>
        </control>
      </composite>

      <composite type="group" layout="row"
        layoutParam="type=VERTICAL; spacing=10">
        <property name="text">グループ2</property>

        <control type="button" style="RADIO">
          <property name="text">ラジオボタン1</property>
        </control>

        <control type="button" style="RADIO">
          <property name="text">ラジオボタン2</property>
        </control>

        <control type="button" style="RADIO">
          <property name="text">ラジオボタン3</property>
          <property name="selection">true</property>
        </control>

        <control type="button" style="RADIO">
          <property name="text">ラジオボタン4</property>
        </control>
      </composite>

    </composite>

    <control type="label" style="SEPARATOR, HORIZONTAL">
      <layoutData name="horizontalAlignment">FILL</layoutData>
    </control>

    <composite type="box" layout="fill"
      layoutParam="type=HORIZONTAL; spacing=5">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <control type="button" id="okButton">
        <property name="text">OK</property>
      </control>
      <control type="button" id="ngButton">
        <property name="text">NG</property>
      </control>
    </composite>

  </window>
</template>

=== seasarorg/uruma-www/src/test/resources/org/seasar/jface/template/TemplateBuilderTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="testTemplate">
	<window id="testApp" title="テストアプリケーション" width="50%" height="50%" x="center"
		y="middle" maxButton="true" minButton="true" closeButton="true" resizable="true"
		image="container.gif" layout="row"
		layoutParam="type=HORIZONTAL; marginHeight=10; marginWidth=10; spacing=10">
		<control id="testButton" type="button">
			<property name="x" value="10"/>
			<property name="y" value="10"/>
			<property name="width" value="100"/>
			<property name="height" value="20"/>
			<property name="text" value="テストボタン1"/>
		</control>
		<control id="testButton2" type="button">
			<property name="x" value="130"/>
			<property name="y" value="30"/>
			<property name="width" value="50"/>
			<property name="height" value="50"/>
			<property name="text" value="テストボタン2"/>
		</control>
		<control id="testButton3" type="button">
			<property name="x" value="130"/>
			<property name="y" value="30"/>
			<property name="width" value="50"/>
			<property name="height" value="50"/>
			<property name="text" value="テストボタン3"/>
			<property name="enabled" value="true"/>
			<property name="visible" value="true"/>
		</control>
		<composite type="box" layout="fill" layoutParam="type=VERTICAL">
			<control type="label">
				<property name="width" value="100"/>
				<property name="height" value="30"/>
				<property name="text" value="テストラベル"/>
				<property name="foregroundColor" value="#FF0000"/>
				<property name="backgroundColor" value="blue"/>
				<property name="toolTip" value="ツールチップ"/>
				<property name="fontSize" value="20"/>
			</control>
			<control type="label">
				<property name="text" value="テストラベル2"/>
				<property name="font" value="ＭＳ 明朝"/>
				<property name="fontStyle" value="BOLD, ITALIC"/>
				<property name="fontSize" value="64"/>
			</control>
		</composite>
		
		<control type="text">
			<property name="text" value="テストテキスト"/>
			<property name="textLimit" value="30"/>
		</control>
		
		<control type="textArea">
			<property name="text" value="テストテキスト"/>
			<property name="textLimit" value="30"/>
		</control>
	</window>
</template>

=== seasarorg/uruma-www/s2jface/src/test/resources/org/seasar/jface/renderer/SpinnerRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="spinnerRendererTest" extends="RendererTest.xml">
  <extends id="spinnerRendererTest" property="title">
    SpinnerRendererTest
  </extends>
  <extends id="contents" />
  <window id="spinnerRendererTest" layout="grid">
    <composite id="contents" type="box">
      <layoutData name="horizontalAlignment">FILL</layoutData>

      <control type="spinner">
        <property name="max">100</property>
        <property name="min">1</property>
        <property name="selection">20</property>
      </control>

      <control type="spinner">
        <property name="max">100</property>
        <property name="min">1</property>
      </control>
    </composite>
  </window>
</template>
