=== seasarorg/uruma-www/src/main/resources/org/seasar/jface/template/s2jface01.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
-->
<!ELEMENT template (window)>
<!ATTLIST template name CDATA #REQUIRED>

<!ELEMENT window (composite | control | property)*>
<!ATTLIST window id CDATA #REQUIRED>
<!ATTLIST window title CDATA #IMPLIED>
<!ATTLIST window x CDATA #IMPLIED>
<!ATTLIST window y CDATA #IMPLIED>
<!ATTLIST window width CDATA #IMPLIED>
<!ATTLIST window height CDATA #IMPLIED>
<!ATTLIST window maxButton (true | false) "true">
<!ATTLIST window minButton (true | false) "true">
<!ATTLIST window closeButton (true | false) "true">
<!ATTLIST window resizable (true | false) "true">
<!ATTLIST window image CDATA #IMPLIED>
<!ATTLIST window layout CDATA #IMPLIED>
<!ATTLIST window layoutParam CDATA #IMPLIED>

<!ELEMENT control (property | layoutData)*>
<!ATTLIST control type CDATA #REQUIRED>
<!ATTLIST control id CDATA #IMPLIED>
<!ATTLIST control style CDATA #IMPLIED>

<!ELEMENT composite (composite | control | property | layoutData)*>
<!ATTLIST composite type CDATA #REQUIRED>
<!ATTLIST composite id CDATA #IMPLIED>
<!ATTLIST composite style CDATA #IMPLIED>
<!ATTLIST composite layout CDATA #IMPLIED>
<!ATTLIST composite layoutParam CDATA #IMPLIED>

<!ELEMENT property EMPTY>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #REQUIRED>
<!ATTLIST property inheritance (none | child | descendant) #IMPLIED>

<!ELEMENT layoutData EMPTY>
<!ATTLIST layoutData name CDATA #REQUIRED>
<!ATTLIST layoutData value CDATA #REQUIRED>

=== seasarorg/uruma-www/s2jface/src/test/resources/org/seasar/jface/renderer/MenuRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="menuRendererTest">
  <window id="menuRendererTest" style="TITLE" layout="grid"
    layoutParam="numColumns=1">
    <property name="title">MenuRendererTest</property>
    <property name="defaultButton">okButton</property>

    <control type="menu">
      <item label="Menu">
        <item>Menu1</item>
        <item>Menu2</item>
      </item>
    </control>

    <control type="label" style="SEPARATOR, HORIZONTAL">
      <layoutData name="horizontalAlignment">FILL</layoutData>
    </control>

    <composite type="box" layout="fill"
      layoutParam="type=HORIZONTAL; spacing=5">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <control type="button" id="okButton">
        <property name="text">OK</property>
      </control>
      <control type="button" id="ngButton">
        <property name="text">NG</property>
      </control>
    </composite>

  </window>
</template>

=== seasarorg/uruma-www/src/test/resources/org/seasar/jface/renderer/TabRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="tabRendererTest">
  <window id="tabRendererTest" title="TabRendererTest" x="center"
    y="middle" minButton="false" maxButton="false" closeButton="false"
    resizable="false" layout="grid" layoutParam="numColumns=1">
    <property name="defaultButton" value="okButton" />

    <composite type="box" layout="fill"
      layoutParam="type=HORIZONTAL; marginHeight=10; marginWidth=10; spacing=10">
      <layoutData name="horizontalAlignment" value="FILL" />

      <control type="tab">
      	<property name="text" value="tab1-1, tab1-2" />
      </control>

      <control type="tab">
      	<property name="text" value="tab2-1, tab2-2, tab2-3" />
      </control>
    </composite>
 
    <control type="label" style="SEPARATOR, HORIZONTAL">
      <layoutData name="horizontalAlignment" value="FILL" />
    </control>

    <composite type="box" layout="fill"
      layoutParam="type=HORIZONTAL; spacing=5">
      <layoutData name="horizontalAlignment" value="FILL" />
      <control type="button" id="okButton">
        <property name="text" value="OK" />
      </control>
      <control type="button" id="ngButton">
        <property name="text" value="NG" />
      </control>
    </composite>

  </window>
</template>

=== seasarorg/uruma-www/s2jface/src/test/resources/org/seasar/jface/renderer/TabRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="tabRendererTest" extends="RendererTest.xml">
  <extends id="tabRendererTest" property="title">
    TabRendererTest
  </extends>
  <extends id="contents" />
  <window id="tabRendererTest" layout="grid">
    <composite id="contents" type="box">
      <layoutData name="horizontalAlignment">FILL</layoutData>

      <control type="tab">
        <property name="text">tab1-1, tab1-2</property>
      </control>

      <control type="tab">
        <property name="text">tab2-1, tab2-2, tab2-3</property>
      </control>
    </composite>
  </window>
</template>

=== seasarorg/uruma-www/src/example/resources/org/seasar/jface/example/janken/DIdeJanken.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="DIdeJanken">
  <window id="janken" layout="grid" layoutParam="numColumns=3">
    <property name="title">DIでジャンケン</property>
    <property name="image">container.gif</property>

    <property name="backgroundColor">white</property>
    <property name="foregroundColor">black</property>
    <property name="fontSize">50</property>
    <property name="alignment">CENTER</property>

    <control type="label">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <property name="text">コンピュータ</property>
    </control>
    <composite type="box">
      <layoutData name="horizontalAlignment">FILL</layoutData>
    </composite>
    <control type="label">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <property name="text">あなた</property>
    </control>

    <control type="label" id="computerWinLabel">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <property name="text">0 勝</property>
    </control>
    <composite type="box">
      <layoutData name="horizontalAlignment">FILL</layoutData>
    </composite>
    <control type="label" id="playerWinLabel">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <property name="text">0 勝</property>
    </control>

    <control type="label" id="computerHandImage">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <property name="image">blank</property>
    </control>
    <control type="label">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <layoutData name="verticalalAlignment">TOP</layoutData>
      <layoutData name="grabExcessHorizontalSpace">true</layoutData>
      <property name="text">vs</property>
      <property name="fontsize">100</property>
    </control>
    <control type="label" id="playerHandImage">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <property name="image">blank</property>
    </control>

    <control type="label" id="messageLabel">
      <layoutData name="horizontalSpan">3</layoutData>
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <property name="text">じゃんけん・・・</property>
    </control>

    <composite type="box" layout="fill"
      layoutParam="spacing=20; marginWidth=20">
      <layoutData name="horizontalSpan">3</layoutData>
      <layoutData name="horizontalAlignment">FILL</layoutData>

      <control type="button" id="guButton">
        <property name="text">グー！</property>
      </control>
      <control type="button" id="cyokiButton">
        <property name="text">チョキ！</property>
      </control>
      <control type="button" id="paButton">
        <property name="text">パー！</property>
      </control>
    </composite>

  </window>
</template>

=== seasarorg/uruma-www/src/test/resources/org/seasar/jface/renderer/SliderRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="sliderRendererTest" extends="RendererTest.xml">
  <extends id="sliderRendererTest" property="title">
    SliderRendererTest
  </extends>
  <extends id="contents" />
  <window id="sliderRendererTest">

    <composite id="contents" type="box">
      <layoutData name="horizontalAlignment">FILL</layoutData>

      <control type="slider">
        <property name="max">100</property>
        <property name="min">0</property>
        <property name="selection">10</property>
        <property name="incriment">5</property>
      </control>

      <control type="slider">
        <property name="max">100</property>
        <property name="min">0</property>
        <property name="incriment">5</property>
        <property name="style">VARTICAL</property>
      </control>

    </composite>
  </window>
</template>

=== seasarorg/uruma-www/src/test/resources/org/seasar/jface/renderer/SpinnerRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="spinnerRendererTest">
  <window id="spinnerRendererTest" title="SpinnerRendererTest"
    x="center" y="middle" minButton="false" maxButton="false"
    closeButton="false" resizable="false" layout="grid"
    layoutParam="numColumns=1">
    <property name="defaultButton">okButton</property>

    <composite type="box" layout="row"
      layoutParam="type=HORIZONTAL; marginHeight=10; marginWidth=10; spacing=10">
      <layoutData name="horizontalAlignment">FILL</layoutData>

      <control type="spinner">
        <property name="max">100</property>
        <property name="min">1</property>
        <property name="selection">20</property>
      </control>

      <control type="spinner">
        <property name="max">100</property>
        <property name="min">1</property>
      </control>
    </composite>

    <control type="label" style="SEPARATOR, HORIZONTAL">
      <layoutData name="horizontalAlignment">FILL</layoutData>
    </control>

    <composite type="box" layout="fill"
      layoutParam="type=HORIZONTAL; spacing=5">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <control type="button" id="okButton">
        <property name="text">OK</property>
      </control>
      <control type="button" id="ngButton">
        <property name="text">NG</property>
      </control>
    </composite>

  </window>
</template>

=== seasarorg/uruma-www/src/test/resources/org/seasar/jface/annotation/EventListenerTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="eventListenerTest">
	<window id="eventListenerTest" layout="grid" layoutParam="numColumns=1">
		<property name="title">EventListenerTest</property>
		<property name="height">400</property>
		<property name="width">600</property>
		
		<composite type="box" layout="grid" layoutParam="numColumns=3">
           	<layoutData name="horizontalAlignment">FILL</layoutData>
           	<layoutData name="verticalAlignment">FILL</layoutData>
           	
			<control type="button" id="button">
           		<layoutData name="grabExcessHorizontalSpace">true</layoutData>
           		<layoutData name="horizontalAlignment">FILL</layoutData>
           		<layoutData name="grabExcessVerticalSpace">true</layoutData>
           		<layoutData name="verticalAlignment">FILL</layoutData>
				<property name="text">button</property>
			</control>
		
			<control type="label" id="mouseLabel" style="BORDER">
           		<layoutData name="grabExcessVerticalSpace">true</layoutData>
           		<layoutData name="verticalAlignment">FILL</layoutData>
				<property name="text">listen Mouse events</property>
			</control>
			
			<control type="textArea" id="text">
           		<layoutData name="grabExcessVerticalSpace">true</layoutData>
           		<layoutData name="verticalAlignment">FILL</layoutData>
				<property name="text">
Text

  and

MouseWheel
				</property>
			</control>
		</composite>
		
        <control type="label" style="SEPARATOR, HORIZONTAL">
            <layoutData name="horizontalAlignment">FILL</layoutData>
        </control>

		<control type="textArea" id="eventLog">
            <layoutData name="grabExcessHorizontalSpace">true</layoutData>
            <layoutData name="horizontalAlignment">FILL</layoutData>
            <layoutData name="grabExcessVerticalSpace">true</layoutData>
            <layoutData name="verticalAlignment">FILL</layoutData>
		    
		</control>
	</window>
</template>
