=== seasarorg/uruma-www/s2jface/src/main/resources/org/seasar/jface/component/factory/s2jface02.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.2//EN" 
	"http://www.seasar.org/dtd/s2jface02.dtd">
-->

<!--==================== ENTITY ====================-->
<!-- type -->
<!ENTITY % boolean
  "(true | false)"
>
<!ENTITY % int
  "CDATA"
>
<!ENTITY % String
  "CDATA"
>
<!-- TODO SWTConstの部分を各場所ごとに指定できる候補の補完にする -->
<!ENTITY % SWTConst
  "CDATA"
>
<!ENTITY % Color
  "CDATA"
>
<!ENTITY % Image
  "CDATA"
>
<!ENTITY % Accelerator
  "CDATA"
>

<!-- attributes -->
<!ENTITY % widgetAttrs
 "id       ID          #IMPLIED
  style    %SWTConst;  #IMPLIED"
>
<!ENTITY % controlAttrs
 "%widgetAttrs;
  background       %Color;      #IMPLIED
  backgroundImage  %Image;      #IMPLIED
  x                %int;        #IMPLIED
  y                %int;        #IMPLIED
  width            %int;        #IMPLIED
  height           %int;        #IMPLIED
  enabled          %boolean;    #IMPLIED
  fontHeight       %int;        #IMPLIED
  fontName         %String;     #IMPLIED
  fontStyle        %SWTConst;   #IMPLIED
  foreground       %Color;      #IMPLIED
  toolTipText      %String;     #IMPLIED
  visible          %boolean;    #IMPLIED"
>
<!ENTITY % compositeAttrs
 "%controlAttrs;
  tabList  %String;  #IMPLIED"
>
<!ENTITY % decorationsAttrs
 "%compositeAttrs;
  defaultButtonId	%String;  #IMPLIED
  image         	%String;  #IMPLIED
  title           	%String;  #IMPLIED"
>
<!ENTITY % itemAttrs
 "%widgetAttrs;
  image  %Image;   #IMPLIED
  text   %String;  #IMPLIED"
>

<!-- layout -->
<!-- TODO レイアウト追加 -->
<!ENTITY % layout
  "fillLayout | gridLayout | rowLayout"
>
<!ENTITY % layoutData
  "gridData | rowData"
>

<!-- control -->
<!-- TODO コントロール定義追加 -->
<!ENTITY % composite
 "combo | composite | group | customTab | spinner | tabFolder | table | tree | customComposite"
>
<!ENTITY % control
 "button | label | list | progressBar | scale | slider | text | textArea | customControl"
>

<!-- elements -->
<!ENTITY % controlElem
  "%layoutData; | menu"
>
<!ENTITY % compositeElem
  "%controlElem; | %layout; | commonAttributes"
>
<!ENTITY % compositeChild
  "%composite; | %control; | include"
>


<!--==================== ELEMENT ====================-->
<!-- template -->
<!ELEMENT template (window | componentDef)>
<!ATTLIST template
  name     %String;  #REQUIRED
  extends  %String;  #IMPLIED
>

<!-- window -->
<!ELEMENT window ((%compositeElem; | menuManager)*, (%compositeChild;)*)>
<!ATTLIST window
  %decorationsAttrs;
  imeInputMode   	%SWTConst;  #IMPLIED
  width          	%int;       #IMPLIED
  height         	%int;       #IMPLIED
  x              	%int;       #IMPLIED
  y              	%int;       #IMPLIED
  minimumWidth   	%int;       #IMPLIED
  minimumHeight  	%int;       #IMPLIED
>

<!-- componentDef -->
<!ELEMENT componentDef (param*, (%composite; | %control;))>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param
  name  %String;  #REQUIRED
>

<!-- include -->
<!ELEMENT include (param*, (%composite; | %control;)*)>
<!ATTLIST include
  name  %String;  #REQUIRED
>

<!-- commonAttributes -->
<!ELEMENT commonAttributes EMPTY>
<!ATTLIST commonAttributes
  background       %Color;      #IMPLIED
  foreground       %Color;      #IMPLIED
  width            %int;        #IMPLIED
  height           %int;        #IMPLIED
  fontHeight       %int;        #IMPLIED
  fontName         %String;     #IMPLIED
  fontStyle        %SWTConst;   #IMPLIED
>

<!-- composite -->
<!ELEMENT composite ((%compositeElem;)*, (%compositeChild;)*)>
<!ATTLIST composite
  %compositeAttrs;
>

<!ELEMENT combo ((%compositeElem;)* , item*, (%compositeChild;)*)>
<!ATTLIST combo
  %compositeAttrs;
  orientation       %SWTConst;  #IMPLIED
  select            %int;       #IMPLIED
  text              %String;    #IMPLIED
  textLimit         %int;       #IMPLIED
  visibleItemCount  %int;       #IMPLIED
>

<!ELEMENT group ((%compositeElem;)*, (%compositeChild;)*)>
<!ATTLIST group
  %compositeAttrs;
  text  %String;  #IMPLIED
>

<!ELEMENT spinner ((%compositeElem;)*, (%compositeChild;)*)>
<!ATTLIST spinner
  %compositeAttrs;
  digits         %int;  #IMPLIED
  increment      %int;  #IMPLIED
  maximum        %int;  #IMPLIED
  minimum        %int;  #IMPLIED
  pageIncrement  %int;  #IMPLIED
  selection      %int;  #IMPLIED
>

<!ELEMENT tabFolder ((%compositeElem;)* , tabItem*, (%compositeChild;)*)>
<!ATTLIST tabFolder
  %compositeAttrs;
  selection  %int;  #IMPLIED
>

<!ELEMENT tabItem EMPTY>
<!ATTLIST tabItem
  %itemAttrs;
  control      %String;  #IMPLIED
  toolTipText  %String;  #IMPLIED
>

<!ELEMENT table ((%compositeElem;)* , tableColumn*, tableItem*, (%compositeChild;)*)>
<!ATTLIST table
  %compositeAttrs;
  columnOrder    %String;   #IMPLIED
  headerVisible  %boolean;  #IMPLIED
  itemCount      %int;      #IMPLIED
  linesVisible   %boolean;  #IMPLIED
  selection      %String;   #IMPLIED
  topIndex       %int;      #IMPLIED
>

<!ELEMENT tableColumn EMPTY>
<!ATTLIST tableColumn
  %itemAttrs;
  alignment    %SWTConst;  #IMPLIED
  moveable     %boolean;   #IMPLIED
  resizable    %boolean;   #IMPLIED
  toolTipText  %String;    #IMPLIED
  width        %int;       #IMPLIED
>

<!-- TODO TableItemの詳細記述 -->
<!ELEMENT tableItem EMPTY>
<!ATTLIST tableItem
  %itemAttrs;
>

<!-- TODO composite記述追加 -->


<!-- control -->
<!ELEMENT button (%controlElem;)*>
<!ATTLIST button
  %controlAttrs;
  alignment  %SWTConst;  #IMPLIED
  image      %Image;     #IMPLIED
  selection  %boolean;   #IMPLIED
  text       %String;    #IMPLIED
>

<!ELEMENT label (%controlElem;)*>
<!ATTLIST label
  %controlAttrs;
  alignment  %SWTConst;  #IMPLIED
  image      %Image;     #IMPLIED
  text       %String;    #IMPLIED
>

<!ELEMENT list ((%controlElem;)*, item*)>
<!ATTLIST list
  %controlAttrs;
  select    %String;  #IMPLIED
  topIndex  %int;     #IMPLIED
>

<!ELEMENT progressBar (%controlElem;)*>
<!ATTLIST progressBar
  %controlAttrs;
  maximum    %int;  #IMPLIED
  minimum    %int;  #IMPLIED
  selection  %int;  #IMPLIED
>

<!ELEMENT scale (%controlElem;)*>
<!ATTLIST scale
  %controlAttrs;
  increment      %int;  #IMPLIED
  maximum        %int;  #IMPLIED
  minimum        %int;  #IMPLIED
  pageIncrement  %int;  #IMPLIED
  selection      %int;  #IMPLIED
>

<!ELEMENT slider (%controlElem;)*>
<!ATTLIST slider
  %controlAttrs;
  increment      %int;  #IMPLIED
  maximum        %int;  #IMPLIED
  minimum        %int;  #IMPLIED
  pageIncrement  %int;  #IMPLIED
  selection      %int;  #IMPLIED
  thumb          %int;  #IMPLIED
>

<!-- TODO control記述追加 -->


<!-- custom -->
<!ELEMENT customComposite ((%compositeElem;)*, property*, (%compositeChild;)*)>
<!ATTLIST customComposite
  type  %String;  #REQUIRED
  %compositeAttrs;
>

<!ELEMENT customControl ((%controlElem;)*, property*)>
<!ATTLIST customControl
  type  %String;  #REQUIRED
  %controlAttrs;
>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property
  name  %String;  #REQUIRED
>


<!-- layout -->
<!ELEMENT fillLayout EMPTY>
<!ATTLIST fillLayout
  marginHeight  %int;       #IMPLIED
  marginWidth   %int;       #IMPLIED
  spacing       %int;       #IMPLIED
  type          %SWTConst;  #IMPLIED
>

<!ELEMENT gridLayout (gridData)?>
<!ATTLIST gridLayout
  horizontalSpacing      %int;      #IMPLIED
  makeColumnsEqualWidth  %boolean;  #IMPLIED
  marginBottom           %int;      #IMPLIED
  marginHeight           %int;      #IMPLIED
  marginLeft             %int;      #IMPLIED
  marginRight            %int;      #IMPLIED
  marginTop              %int;      #IMPLIED
  marginWidth            %int;      #IMPLIED
  numColumns             %int;      #IMPLIED
  verticalSpacing        %int;      #IMPLIED
>

<!ELEMENT rowLayout (rowData)?>
<!ATTLIST rowLayout
  fill          %boolean;   #IMPLIED
  justify       %boolean;   #IMPLIED
  marginBottom  %int;       #IMPLIED
  marginHeight  %int;       #IMPLIED
  marginLeft    %int;       #IMPLIED
  marginRight   %int;       #IMPLIED
  marginTop     %int;       #IMPLIED
  marginWidth   %int;       #IMPLIED
  pack          %boolean;   #IMPLIED
  spacing       %int;       #IMPLIED
  type          %SWTConst;  #IMPLIED
  wrap          %boolean;   #IMPLIED
>

<!ELEMENT gridData EMPTY>
<!ATTLIST gridData
  exclude                    %boolean;   #IMPLIED
  grabExcessHorizontalSpace  %boolean;   #IMPLIED
  grabExcessVerticalSpace    %boolean;   #IMPLIED
  heightHint                 %int;       #IMPLIED
  horizontalAlignment        %SWTConst;  #IMPLIED
  horizontalIndent           %int;       #IMPLIED
  horizontalSpan             %int;       #IMPLIED
  minimumHeight              %int;       #IMPLIED
  minimumWidth               %int;       #IMPLIED
  verticalAlignment          %SWTConst;  #IMPLIED
  verticalIndent             %int;       #IMPLIED
  verticalSpan               %int;       #IMPLIED
  widthHint                  %int;       #IMPLIED
>

<!ELEMENT rowData EMPTY>
<!ATTLIST rowData
  exclude  %boolean;  #IMPLIED
  height   %int;      #IMPLIED
  width    %int;      #IMPLIED
>

<!-- item -->
<!ELEMENT item (#PCDATA)*>
<!ATTLIST item
  text  %String;  #IMPLIED
>

<!-- menu -->
<!ELEMENT menu (menu | menuItem)*>
<!ATTLIST menu
  %widgetAttrs;
  defaultItem  %String;   #IMPLIED
  enabled      %boolean;  #IMPLIED
  x            %int;      #IMPLIED
  y            %int;      #IMPLIED
  visible      %boolean;  #IMPLIED
>

<!ELEMENT menuItem (menu | menuItem)*>
<!ATTLIST menuItem
  %widgetAttrs;
  %itemAttrs;
  accelerator  %Accelerator;  #IMPLIED
  enabled      %boolean;      #IMPLIED
  selection    %boolean;      #IMPLIED
>

<!-- TODO MenuManagerがwindow以外にもつけられる場合はcontrolElemsなどに追加 -->
<!ELEMENT menuManager (action | separator | menuManager)*>
<!ATTLIST menuManager
  text  %String;  #IMPLIED
>

<!ELEMENT action (#PCDATA)>

<!ELEMENT separator EMPTY>

=== seasarorg/uruma-www/s2jface/src/test/resources/org/seasar/jface/renderer/impl/ButtonRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.2//EN" 
  "http://www.seasar.org/dtd/s2jface02.dtd">
<template name="WindowRendererTest">
  <window id="ButtonRendererTest" title="ButtonRendererTest"
    image="/images/component.gif" defaultButtonId="okButton">
    <gridLayout numColumns="1">
      <gridData horizontalAlignment="FILL" />
    </gridLayout>

    <composite id="contents">
      <rowLayout type="HORIZONTAL" marginWidth="10" marginHeight="10"
        spacing="10" />
      <commonAttributes fontHeight="20" />

      <composite>
        <rowLayout type="VERTICAL" spacing="10" />
        <button text="プッシュボタン" toolTipText="ツールチップテキスト" />
        <button style="FLAT" text="フラットボタン" />
        <button style="CHECK" text="チェックボタン(OFF)" />
        <button style="CHECK" text="チェックボタン(ON)" selection="true" />
        <button style="TOGGLE" text="トグルボタン(OFF)" />
        <button style="TOGGLE" text="トグルボタン(ON)" selection="true" />
        <button text="フォントを変更" fontName="ＭＳ 明朝" fontHeight="15"
          fontStyle="BOLD, ITALIC" />
      </composite>

      <composite>
        <rowLayout type="VERTICAL" spacing="10">
          <rowData width="30" height="30" />
        </rowLayout>

        <button style="ARROW, UP" />
        <button style="ARROW, RIGHT" />
        <button style="ARROW, DOWN" />
        <button style="ARROW, LEFT" />
      </composite>
    </composite>

    <label style="SEPARATOR, HORIZONTAL" />

    <composite>
      <fillLayout type="HORIZONTAL" spacing="5" />

      <button id="okButton" text="OK"></button>
      <button id="ngButton" text="NG"></button>
    </composite>
  </window>
</template>

=== seasarorg/uruma-www/s2jface/src/example/resources/org/seasar/jface/example/janken/DIdeJanken.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.2//EN" 
	"http://www.seasar.org/dtd/s2jface02.dtd">

<template name="DIdeJanken">
  <window id="janken" title="DIでジャンケン" image="container.gif" background="white">
    <commonAttributes background="white" foreground="black" fontHeight="50"/>
    <gridLayout numColumns="3" marginHeight="5" marginWidth="5">
      <gridData horizontalAlignment="CENTER" verticalAlignment="CENTER" />
    </gridLayout>

    <label text="コンピュータ" />
    <composite />
    <label text="あなた" />

    <label id="computerWinLabel" text="0 勝" />
    <composite />
    <label id="playerWinLabel" text="0 勝" />

    <label id="computerHandImage" image="blank" />
    <label text="vs" fontHeight="100">
      <gridData verticalAlignment="CENTER"
        grabExcessHorizontalSpace="true" />
    </label>
    <label id="playerHandImage" image="blank" />

    <label id="messageLabel" text="じゃんけん・・・" alignment="CENTER">
      <gridData horizontalSpan="3" horizontalAlignment="FILL"/>
    </label>

    <composite>
      <fillLayout spacing="20" marginWidth="20" />
      <gridData horizontalSpan="3" />

      <button id="guButton" text="グー!" />
      <button id="cyokiButton" text="チョキ!" />
      <button id="paButton" text="パー!" />
    </composite>
  </window>
</template>
