=== seasarorg/uruma-www/s2jface/src/main/resources/org/seasar/jface/template/s2jface01.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
-->
<!ELEMENT template (
        window
)>

<!ATTLIST template name CDATA #REQUIRED>

<!ELEMENT window (property | control | composit)*>

<!ATTLIST window id CDATA #REQUIRED>
<!ATTLIST window title CDATA #REQUIRED>
<!ATTLIST window x CDATA #REQUIRED>
<!ATTLIST window y CDATA #REQUIRED>
<!ATTLIST window x CDATA #REQUIRED>
<!ATTLIST window maxButton (true | false) "true">
<!ATTLIST window minButton (true | false) "true">
<!ATTLIST window closeButton (true | false) "true">
<!ATTLIST window resizable (true | false) "true">
<!ATTLIST window layout CDATA #REQUIRED>
<!ATTLIST window layoutParam CDATA #REQUIRED>

<!ELEMENT property EMPTY>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #REQUIRED>

<!ELEMENT control (layoutData | property)*>
<!ATTLIST control type CDATA #REQUIRED>
<!ATTLIST control id CDATA #REQUIRED>

<!ELEMENT layoutData EMPTY>
<!ATTLIST layoutData name CDATA #REQUIRED>
<!ATTLIST layoutData value CDATA "FILL">

<!ELEMENT composit (layoutData | control)*>

=== seasarorg/uruma-www/s2jface/src/test/resources/org/seasar/jface/renderer/GroupRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="groupRendererTest">
  <window id="groupRendererTest" title="GroupRendererTest" x="center"
    y="middle" layout="row"
    layoutParam="type=HORIZONTAL; marginHeight=10; marginWidth=10; spacing=10">

    <composite type="group" layout="row"
      layoutParam="type=VERTICAL; spacing=10">
      <property name="text" value="グループ1" />

      <control type="button" style="RADIO">
        <property name="text" value="ラジオボタン1" />
      </control>

      <control type="button" style="RADIO">
        <property name="text" value="ラジオボタン2" />
      </control>

      <control type="button" style="RADIO">
        <property name="text" value="ラジオボタン3" />
      </control>
    </composite>

    <composite type="group" layout="row"
      layoutParam="type=VERTICAL; spacing=10">
      <property name="text" value="グループ2" />

      <control type="button" style="RADIO">
        <property name="text" value="ラジオボタン1" />
      </control>

      <control type="button" style="RADIO">
        <property name="text" value="ラジオボタン2" />
      </control>

      <control type="button" style="RADIO">
        <property name="text" value="ラジオボタン3" />
        <property name="selection" value="true"/>
      </control>

      <control type="button" style="RADIO">
        <property name="text" value="ラジオボタン4" />
      </control>

    </composite>
  </window>
</template>
