=== seasarorg/uruma-www/s2jface/src/main/resources/org/seasar/jface/template/s2jface01.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
-->
<!ELEMENT template (
        window
)>

<!ATTLIST template name CDATA #REQUIRED>

<!ELEMENT window (property | control | composit)*>

<!ATTLIST window id CDATA #REQUIRED>
<!ATTLIST window title CDATA #REQUIRED>
<!ATTLIST window x CDATA #REQUIRED>
<!ATTLIST window y CDATA #REQUIRED>
<!ATTLIST window x CDATA #REQUIRED>
<!ATTLIST window maxButton (true | false) "true">
<!ATTLIST window minButton (true | false) "true">
<!ATTLIST window closeButton (true | false) "true">
<!ATTLIST window resizable (true | false) "true">
<!ATTLIST window layout CDATA #REQUIRED>
<!ATTLIST window layoutParam CDATA #REQUIRED>

<!ELEMENT property EMPTY>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #REQUIRED>

<!ELEMENT control (layoutData | property)*>
<!ATTLIST control type CDATA #REQUIRED>
<!ATTLIST control id CDATA #REQUIRED>

<!ELEMENT layoutData EMPTY>
<!ATTLIST layoutData name CDATA #REQUIRED>
<!ATTLIST layoutData value CDATA "FILL">

<!ELEMENT composit (layoutData | control)*>

=== seasarorg/uruma-www/s2jface/src/test/resources/org/seasar/jface/renderer/LabelRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="labelRendererTest" extends="RendererTest.xml">
  <extends id="labelRendererTest" property="title">
    LabelRendererTest
  </extends>
  <extends id="contents" />
  
  <window id="labelRendererTest">
    <composite id="contents" type="box">
      <composite type="box" layout="row" layoutParam="type=VERTICAL">
        <control type="label">
          <property name="text">ラベル</property>
          <property name="toolTip">ツールチップテキスト</property>
        </control>

        <control type="label" style="BORDER">
          <property name="text">枠付きラベル</property>
        </control>

        <control type="label">
          <property name="image">../template/container.gif</property>
        </control>

        <control type="label">
          <property name="image">
            org/seasar/jface/template/container.gif
          </property>
        </control>

        <control type="label" style="BORDER">
          <property name="text">複数行テキスト1行目\n\t複数行テキスト2行目\n3行目</property>
        </control>

        <control type="label" style="WRAP, BORDER">
          <property name="text">
            WRAPスタイルを適用することで、長い文字列は折り返して表示されます。
          </property>
          <property name="fontSize">12</property>
          <property name="width">200</property>
          <property name="height">100</property>
        </control>
      </composite>

      <composite type="box" layout="row" layoutParam="type=VERTICAL">
        <property name="width">300</property>

        <control type="label" style="BORDER, LEFT">
          <property name="text">左寄せ1</property>
        </control>

        <control type="label" style="BORDER">
          <property name="text">左寄せ2</property>
          <property name="alignment">LEFT</property>
        </control>

        <control type="label" style="BORDER, CENTER">
          <property name="text">中央1</property>
        </control>

        <control type="label" style="BORDER">
          <property name="text">中央2</property>
          <property name="alignment">CENTER</property>
        </control>

        <control type="label" style="BORDER, RIGHT">
          <property name="text">右寄せ1</property>
        </control>

        <control type="label" style="BORDER">
          <property name="text">右寄せ2</property>
          <property name="alignment">RIGHT</property>
        </control>

        <control type="label" style="SEPARATOR, HORIZONTAL" />

        <control type="label" style="SEPARATOR, VERTICAL">
          <property name="height">100</property>
        </control>

        <control type="label" style="BORDER, CENTER">
          <property name="text">色・フォントを変更</property>
          <property name="font">ＭＳ 明朝</property>
          <property name="fontSize">15</property>
          <property name="fontStyle">BOLD, ITALIC</property>
          <property name="foregroundColor">yellow</property>
          <property name="backgroundColor">blue</property>
        </control>

      </composite>
    </composite>
  </window>
</template>

=== seasarorg/uruma-www/s2jface/src/test/resources/org/seasar/jface/renderer/ScaleRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="scaleRendererTest" extends="RendererTest.xml">
  <extends id="scaleRendererTest" property="title">
    ScaleRendererTest
  </extends>
  <extends id="contents" />
  <window id="scaleRendererTest" layout="grid">

    <composite id="contents" type="box">
      <layoutData name="horizontalAlignment">FILL</layoutData>

      <control type="scale">
        <property name="max">100</property>
        <property name="min">0</property>
        <property name="selection">10</property>
        <property name="incriment">5</property>
      </control>

      <control type="scale">
        <property name="max">100</property>
        <property name="min">0</property>
        <property name="incriment">1</property>
        <property name="style">VARTICAL</property>
      </control>
    </composite>

  </window>
</template>

=== seasarorg/uruma-www/s2jface/src/test/resources/org/seasar/jface/renderer/ButtonRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="buttonRendererTest">
  <window id="buttonRendererTest" title="ButtonRendererTest" x="center"
    y="middle" minButton="false" maxButton="false" closeButton="false"
    resizable="false" layout="grid" layoutParam="numColumns=1">
    <property name="defaultButton">okButton</property>

    <composite type="box" layout="row"
      layoutParam="type=HORIZONTAL; marginHeight=10; marginWidth=10; spacing=10">
      <property name="fontSize">20</property>
      <layoutData name="horizontalAlignment">FILL</layoutData>

      <composite type="box" layout="row"
        layoutParam="type=VERTICAL; spacing=10">
        <!-- styleを省略した場合、style="PUSH" となります -->
        <control type="button">
          <property name="text">プッシュボタン</property>
          <property name="toolTip">ツールチップテキスト</property>
        </control>

        <control type="button" style="FLAT">
          <property name="text">フラットボタン</property>
        </control>

        <control type="button" style="RADIO">
          <property name="text">ラジオボタン</property>
        </control>

        <control type="button" style="CHECK">
          <property name="text">チェックボタン(OFF)</property>
        </control>

        <control type="button" style="CHECK">
          <property name="text">チェックボタン(ON)</property>
          <property name="selection">true</property>
        </control>

        <control type="button" style="TOGGLE">
          <property name="text">トグルボタン(OFF)</property>
        </control>

        <control type="button" style="TOGGLE">
          <property name="text">トグルボタン(ON)</property>
          <property name="selection">true</property>
        </control>

        <control type="button">
          <property name="text">フォントを変更</property>
          <property name="font">ＭＳ 明朝</property>
          <property name="fontSize">15</property>
          <property name="fontStyle">BOLD, ITALIC</property>
        </control>
      </composite>

      <composite type="box" layout="row"
        layoutParam="type=VERTICAL; spacing=10">
        <property name="width">30</property>
        <property name="height">30</property>

        <control type="button" style="ARROW, UP" />

        <control type="button" style="ARROW, RIGHT" />

        <control type="button" style="ARROW, DOWN" />

        <control type="button" style="ARROW, LEFT" />
      </composite>
    </composite>

    <control type="label" style="SEPARATOR, HORIZONTAL">
      <layoutData name="horizontalAlignment">FILL</layoutData>
    </control>

    <composite type="box" layout="fill"
      layoutParam="type=HORIZONTAL; spacing=5">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <control type="button" id="okButton">
        <property name="text">OK</property>
      </control>
      <control type="button" id="ngButton">
        <property name="text">NG</property>
      </control>
    </composite>

  </window>
</template>

=== seasarorg/uruma-www/uruma/src/test/resources/org/seasar/jface/template/TemplateBuilderTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN"
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="testTemplate">
  <window id="testApp" layout="row"
    layoutParam="type=HORIZONTAL; marginHeight=10; marginWidth=10; spacing=10">
    <property name="title">テストアプリケーション</property>
    <property name="width">50%</property>
    <property name="height">50%</property>
    <property name="x">center</property>
    <property name="y">middle</property>
    <property name="image">container.gif</property>

    <control id="testButton" type="button">
      <property name="x">10</property>
      <property name="y">10</property>
      <property name="width">100</property>
      <property name="height">20</property>
      <property name="text">テストボタン1</property>
    </control>

    <control id="testButton2" type="button">
      <property name="x">130</property>
      <property name="y">30</property>
      <property name="width">100</property>
      <property name="height">50</property>
      <property name="text">テストボタン2</property>
    </control>

    <control id="testButton3" type="button">
      <property name="x">130</property>
      <property name="y">30</property>
      <property name="width">50</property>
      <property name="height">50</property>
      <property name="text">テストボタン3</property>
      <property name="enabled">true</property>
      <property name="visible">true</property>
    </control>

    <composite type="box" layout="fill" layoutParam="type=VERTICAL">
      <control type="label">
        <property name="width">100</property>
        <property name="height">30</property>
        <property name="text">テストラベル</property>
        <property name="foregroundColor">#FF0000</property>
        <property name="backgroundColor">blue</property>
        <property name="toolTip">ツールチップ</property>
        <property name="fontSize">20</property>
      </control>

      <control type="label">
        <property name="text">テストラベル2</property>
        <property name="font">ＭＳ 明朝</property>
        <property name="fontStyle">BOLD, ITALIC</property>
        <property name="fontSize">64</property>
      </control>

    </composite>

    <control type="text">
      <property name="text">テストテキスト</property>
      <property name="textLimit">30</property>
    </control>

    <control type="textArea">
      <property name="text">テストテキスト</property>
      <property name="textLimit">30</property>
    </control>

  </window>
</template>

=== seasarorg/uruma-www/s2jface/src/test/resources/org/seasar/jface/renderer/ProgressBarRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="progressBarRendererTest" extends="RendererTest.xml">
  <extends id="progressBarRendererTest" property="title">
    ProgressBarRendererTest
  </extends>
  <extends id="contents" />

  <window id="progressBarRendererTest">
    <composite id="contents" type="box">
      <layoutData name="horizontalAlignment">FILL</layoutData>

      <control type="progressBar">
        <property name="max">100</property>
        <property name="min">0</property>
        <property name="selection">10</property>
      </control>

      <control type="progressBar" style="VERTICAL">
        <property name="max">100</property>
        <property name="min">0</property>
      </control>
      
      <control type="progressBar" style="VERTICAL, SMOOTH">
        <property name="max">100</property>
        <property name="min">0</property>
        <property name="selection">66</property>
      </control>
    </composite>

  </window>
</template>

=== seasarorg/uruma-www/uruma/src/test/resources/org/seasar/jface/template/TemplateBuilderTest6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN"
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="testTemplate" extends="templateBuilderTest.xml">
  <extends id="testButton" replace="true"/>

  <window id="templateBuilderTest6" layout="fill">
    <control id="testButton" type="button">
      <property name="x">30</property>
      <property name="y">40</property>
      <property name="width">100</property>
      <property name="height">200</property>
      <property name="text">override</property>
    </control>
  </window>
</template>

=== seasarorg/uruma-www/s2jface/src/test/resources/org/seasar/jface/renderer/RendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="rendererTest">
  <window id="rendererTest" style="TITLE" layout="grid"
    layoutParam="numColumns=1">
    <property name="title">RendererTest</property>
    <property name="defaultButton">okButton</property>

    <composite id="contents" type="box" layout="row"
      layoutParam="type=HORIZONTAL; margin=10; spacing=10">
      <property name="fontSize">20</property>
      <layoutData name="horizontalAlignment">FILL</layoutData>
    </composite>

    <control type="label" style="SEPARATOR, HORIZONTAL">
      <layoutData name="horizontalAlignment">FILL</layoutData>
    </control>

    <composite type="box" layout="fill"
      layoutParam="type=HORIZONTAL; spacing=5">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <control type="button" id="okButton">
        <property name="text">OK</property>
      </control>
      <control type="button" id="ngButton">
        <property name="text">NG</property>
      </control>
    </composite>

  </window>
</template>

=== seasarorg/uruma-www/s2jface/src/test/resources/org/seasar/jface/renderer/CustomTabRendererTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template PUBLIC "-//SEASAR//DTD S2JFace 0.1//EN" 
	"http://www.seasar.org/dtd/s2jface01.dtd">
<template name="customTabRendererTest">
  <window id="customTabRendererTest" title="CustomTabRendererTest" x="center"
    y="middle" minButton="false" maxButton="false" closeButton="false"
    resizable="false" layout="grid" layoutParam="numColumns=1">
    <property name="defaultButton">okButton</property>

    <composite type="box" layout="fill"
      layoutParam="type=HORIZONTAL; marginHeight=10; marginWidth=10; spacing=10">
      <layoutData name="horizontalAlignment">FILL</layoutData>

      <control type="customTab">
      	<property name="simpleStyle">true</property>
        <property name="text">tab1-1, tab1-2</property>
      </control>

      <control type="customTab">
        <property name="closeButton">true</property>
        <property name="text">tab2-1, tab2-2, tab2-3</property>
      </control>
    </composite>

    <control type="label" style="SEPARATOR, HORIZONTAL">
      <layoutData name="horizontalAlignment">FILL</layoutData>
    </control>

    <composite type="box" layout="fill"
      layoutParam="type=HORIZONTAL; spacing=5">
      <layoutData name="horizontalAlignment">FILL</layoutData>
      <control type="button" id="okButton">
        <property name="text">OK</property>
      </control>
      <control type="button" id="ngButton">
        <property name="text">NG</property>
      </control>
    </composite>

  </window>
</template>
